name: LaTeX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: D9901r0.tex
          latexmk_shell_escape: true
          
      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: D9901
          path: D9901r0.pdf
